/* eslint-disable linebreak-style */
/* eslint-disable quotes */
/* eslint-disable linebreak-style */
/* eslint-disable object-curly-spacing */
/* eslint-disable max-len */
/* eslint-disable linebreak-style */
/* eslint-disable eol-last */
const samplePosts = [
  { sipzCount: -3, commentsCount: 195, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (835).jpg', postTitle: "Quam saepe magnam facilis dolores consequatur in. Fuga doloribus placeat tempora. Sunt molestiae sequi est laudantium. Aut enim rerum vero dolor perspiciatis consectetur sed minima blanditiis. Aliquid illum ea eveniet esse voluptatem quod neque illo voluptas.", userName: 'Neha Runolfsson', bakeryName: 'b/catBread', timePosted: 'Wed Feb 27 2019 17:26:31 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: -31, commentsCount: 77, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (689).jpg', postTitle: "Debitis dolor et est alias voluptas corrupti tempore quae. Non dolorem porro id est voluptate non. Quasi omnis dolore adipisci ex dignissimos maxime rerum dolorem eaque. Nisi et harum pariatur et qui. Quia voluptatibus placeat porro sint architecto architecto.", userName: 'Eliane Nitzsche', bakeryName: 'b/JudgeBredd', timePosted: 'Sat Dec 01 2018 15:29:11 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: -100, commentsCount: 200, postType: 'text', postText: `Sed voluptas enim rerum sed modi dolorem ut pariatur. Temporibus sed autem ut quam sunt. Nobis enim aut soluta.

Voluptatem eos voluptate ad delectus blanditiis itaque. Dolor molestias quis corrupti. Error quae eos dolores fugiat ea mollitia sint. Aut fugit ratione et.

Quis nihil cupiditate cum voluptatum a eligendi. Ut qui totam nihil voluptas omnis quia dolore libero. Ipsa sit praesentium nihil sunt exercitationem. Consequatur aut enim eligendi aperiam aliquam. Dolor quos et cupiditate.`, imageURL: null, postTitle: "Deserunt velit quaerat neque. Repellendus at pariatur possimus blanditiis facere ab magnam recusandae. Autem magni iusto alias itaque est. Molestiae vel nihil doloribus. Voluptatem reprehenderit autem qui.", userName: 'Ova Wilderman', bakeryName: 'b/bred', timePosted: 'Mon Mar 11 2019 09:54:17 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -85, commentsCount: 33, postType: 'text', postText: `Aut incidunt in maxime qui voluptatem facere quia ipsam. Ut tenetur consequatur quasi eos dolorem assumenda ea minus. Explicabo rerum debitis esse velit. Omnis minima laudantium cum laudantium perspiciatis et praesentium recusandae. Molestiae minus consequatur natus dolores provident sed sapiente qui. Nobis quo ea illum neque.

Sit numquam officiis. Est aut consequatur eos iusto. Eum labore rem et accusamus id blanditiis dolore. Soluta itaque assumenda voluptatum illo autem necessitatibus cum quis.

Molestiae quo fuga nostrum iure. Qui sit quaerat. Et aut consectetur. Nemo repellat fugiat sed aspernatur pariatur nesciunt dolorem nam aut.`, imageURL: null, postTitle: "Labore dignissimos neque hic. Tempore minima autem laboriosam quis. Provident fuga et ea aut aut qui vitae beatae reprehenderit.", userName: 'Griffin Hahn', bakeryName: 'b/catBread', timePosted: 'Tue Feb 19 2019 11:01:05 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: 20, commentsCount: 5, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (628).jpg', postTitle: "Quisquam quia rerum quia omnis. Qui consectetur voluptatem reiciendis atque qui totam tempora culpa quia.", userName: 'Mose Kihn', bakeryName: 'b/JudgeBredd', timePosted: 'Mon Jul 16 2018 12:02:44 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 239, commentsCount: 51, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (946).jpg', postTitle: "Omnis non enim dolorem animi quasi delectus autem omnis ea. In magnam sint ex ea eveniet ducimus tempora voluptatibus. Aut explicabo atque quidem tempora ducimus aliquid adipisci asperiores quos. Et ab et mollitia enim tempora aut laudantium.", userName: 'Cayla Stiedemann', bakeryName: 'b/JudgeBredd', timePosted: 'Fri Jun 29 2018 09:24:35 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -13, commentsCount: 43, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (842).jpg', postTitle: "Recusandae aliquid quo quas pariatur sit. Repellendus et cum sed aut. Quasi quam omnis et reprehenderit eos voluptatem dolores voluptatibus. Commodi autem qui velit ratione architecto possimus dolorem minus nulla. Quas expedita eveniet.", userName: 'Quinton Considine', bakeryName: 'b/HoneyOat', timePosted: 'Sun Jul 08 2018 02:13:42 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -3, commentsCount: 1, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (635).jpg', postTitle: "Velit id alias eum dolores et dolore modi. Ut inventore rerum minus reprehenderit quia architecto reprehenderit. Porro eum alias ipsam enim quo harum. Dolores accusantium neque qui beatae voluptas.", userName: 'Bud Homenick', bakeryName: 'b/bred', timePosted: 'Wed Jan 23 2019 08:52:46 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: 134, commentsCount: 176, postType: 'text', postText: `Voluptas enim sequi sit voluptates. Animi sint non rerum. Rem et suscipit asperiores ut minus ratione.

Necessitatibus et repellat quia ab nihil. Ratione quasi mollitia. Fugit pariatur reprehenderit minus aperiam voluptatem.

Fugit consequatur enim. Quisquam autem rerum odio voluptatibus vero. Quidem inventore consequuntur vitae reiciendis doloremque expedita nisi. Autem nemo quasi aliquid eos sit maxime mollitia. Autem maxime error.`, imageURL: null, postTitle: "Illum magni earum quia id mollitia. Similique incidunt quis repellat illo vitae quisquam expedita magnam quisquam. Earum illo beatae rem est est enim. Beatae eligendi fugit commodi est.", userName: 'Chelsie Reilly', bakeryName: 'b/HoneyOat', timePosted: 'Sat Sep 01 2018 04:15:46 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 69, commentsCount: 52, postType: 'text', postText: `Nemo quis quis amet cupiditate autem. Vero quis ducimus dolor dolorem quos dignissimos voluptate cupiditate odio. Enim tempora rerum qui aut neque consequatur vero dolor ullam. Iure iure sapiente dicta aspernatur voluptatem.

Velit unde quos provident. Amet eius magni vel placeat quas atque. Aut sit vero dolor rem iusto pariatur qui eligendi. Animi asperiores dolores deleniti sequi nobis vel occaecati nulla est. Rerum et quos quia ducimus quo. Omnis omnis nisi totam voluptas aut et.

Et similique magnam. Sit nostrum harum dolores quis. Voluptates explicabo aut cum consequuntur veniam tempore doloribus illo enim. Et facilis ut.`, imageURL: null, postTitle: "Voluptatibus temporibus quis assumenda delectus sit reprehenderit. Eius recusandae aperiam quia quia rem ipsum animi dolorem. Autem occaecati eligendi nemo autem quia libero. Dolore et id nesciunt dolores ab enim repellendus et. Ipsam occaecati porro officia laudantium sapiente dolorem.", userName: 'Florence Beier DVM', bakeryName: 'b/JudgeBredd', timePosted: 'Sun Jan 27 2019 02:11:24 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: 56, commentsCount: 86, postType: 'text', postText: `Vero recusandae sed omnis. Voluptas alias ex tenetur omnis. Distinctio sed ut eos ex temporibus voluptas quam et perspiciatis.

Ea ipsum voluptas esse sint. Nam nam consequatur omnis quod adipisci doloremque sed officia. Molestiae ut officia. Repellendus ratione nobis beatae ipsam dolores et nostrum atque.

Praesentium sed officia sint. Unde doloribus iure odit quo aspernatur ipsa repudiandae consectetur. Quas officiis inventore eum. Iure est exercitationem consequatur magnam aut reprehenderit enim. Non aut ex ipsa non voluptas. Sed incidunt et quia ut necessitatibus molestiae nostrum placeat dolores.`, imageURL: null, postTitle: "Voluptatum ut est eos culpa necessitatibus dolorem. Cumque at amet omnis est vero.", userName: 'Josianne Stark', bakeryName: 'b/catBread', timePosted: 'Sat Nov 24 2018 18:29:50 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: 51, commentsCount: 83, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (836).jpg', postTitle: "Quas expedita voluptatibus voluptates sint iste. Nihil molestiae nostrum vel odit cupiditate temporibus rerum et amet. Quia voluptatem sed rem repellat. Quidem vitae nesciunt similique at at.", userName: 'Eric Wolff', bakeryName: 'b/Sourdough', timePosted: 'Tue Nov 27 2018 04:41:41 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: 7, commentsCount: 52, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (684).jpg', postTitle: "Ullam corrupti inventore possimus corporis. Asperiores eaque eum aut modi enim sunt. Sint ut exercitationem dignissimos nobis nesciunt. Vel quis repudiandae vero. Commodi reiciendis itaque sed totam eligendi tenetur asperiores sit est. Ducimus asperiores aut vitae atque blanditiis id maxime.", userName: 'Kelsi Ledner', bakeryName: 'b/JudgeBredd', timePosted: 'Wed Aug 08 2018 09:26:11 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -69, commentsCount: 185, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (664).jpg', postTitle: "Officia ut odio quis laboriosam quas. Ex labore ea provident itaque. Tempora est omnis ad commodi aut.", userName: 'Mabelle Conroy', bakeryName: 'b/HoneyOat', timePosted: 'Sun Jul 01 2018 23:12:10 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 96, commentsCount: 120, postType: 'text', postText: `Molestiae aut et quidem odio beatae blanditiis ut accusamus. Mollitia facere similique dolorem voluptate molestiae et cupiditate atque. Enim et nobis rerum voluptates. Eius illum optio non qui corrupti eius cupiditate omnis esse. Culpa natus doloremque.

Qui quis illo officiis qui inventore laborum ut ex earum. Quam quibusdam necessitatibus aut nihil repellat animi. Sunt alias neque autem dolore distinctio quas debitis. Beatae quia voluptates. Magni et ea fuga in et saepe consectetur cum. Error et pariatur dolores sed.

Amet eum voluptate ratione voluptatem nulla magnam. Ut numquam sed vel unde voluptatem. Minima qui necessitatibus excepturi voluptas et officiis. Aut eum est soluta. Vel fugit enim voluptatem vero modi ad ut quia eveniet. Minima rem laborum et cumque est.`, imageURL: null, postTitle: "Sint non qui rerum error. Enim voluptatem optio consequatur exercitationem ut facere. Ut est quos id nobis. Veniam aut iure.", userName: 'Katharina Gerhold', bakeryName: 'b/HoneyOat', timePosted: 'Wed Sep 19 2018 22:19:03 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -33, commentsCount: 218, postType: 'text', postText: `Est quibusdam perferendis ut. Quia non tenetur corporis tempora. Dolores dolor ratione perferendis aliquid autem et.

Rerum et voluptas enim quos voluptas ipsum velit temporibus modi. Ullam ipsam iusto itaque est voluptates repellat. Voluptatem dignissimos et quisquam vel. Consequuntur expedita et doloremque rerum recusandae in officia totam.

Ut ut ipsam. Ea et doloremque. Voluptas consequatur harum quis ab natus aut inventore nostrum consectetur.`, imageURL: null, postTitle: "Quidem inventore laboriosam fugiat est libero. Rerum fuga fugiat repellendus eum officia qui ipsum nihil. Ipsam repellat non. Dolorem cumque nihil non soluta optio et. Ea quia ab ullam aut sed nam.", userName: 'Chelsie Kovacek', bakeryName: 'b/wholeWheat', timePosted: 'Sat Jun 08 2019 06:20:35 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -81, commentsCount: 199, postType: 'text', postText: `Quidem nesciunt eveniet. Velit molestiae dolorem. Ad nisi aut cumque sit accusamus sed ea sit.

Aspernatur nisi at quo nulla. Iure et amet dignissimos sapiente et perspiciatis. Eligendi nihil provident nulla.

Omnis eveniet temporibus. Aliquid occaecati voluptatem vel. Et et quis quas tenetur ratione reprehenderit nesciunt enim beatae. Animi consequuntur accusamus numquam temporibus quidem suscipit.`, imageURL: null, postTitle: "Vero et doloremque. Ea nobis blanditiis voluptas aut eligendi ipsa. Suscipit cupiditate inventore facere nesciunt. Odio asperiores fugiat.", userName: 'Afton Schuster', bakeryName: 'b/wholeWheat', timePosted: 'Mon Mar 25 2019 21:55:51 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 118, commentsCount: 65, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (609).jpg', postTitle: "Animi inventore ea ad. Vel eos illum perspiciatis ut ut atque est odio. Aperiam velit omnis quisquam. Dicta placeat culpa illo culpa. Reiciendis vitae est non. Consectetur ipsam et.", userName: 'Kadin Weissnat', bakeryName: 'b/HoneyOat', timePosted: 'Mon Jul 16 2018 17:30:44 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 158, commentsCount: 120, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (563).jpg', postTitle: "Harum non exercitationem. Illo corporis possimus natus neque ea voluptatem. Aliquam corrupti praesentium. Ducimus nesciunt aut porro commodi voluptas nisi. Ipsam blanditiis aut reprehenderit facilis voluptate voluptatibus tempore dolorum.", userName: 'Dianna Bailey', bakeryName: 'b/bred', timePosted: 'Thu Nov 08 2018 02:22:55 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: -99, commentsCount: 39, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (704).jpg', postTitle: "Aut aperiam voluptates qui autem beatae et ut. Tempore sunt minus beatae dolorem laboriosam dolor eos et. Omnis eaque qui numquam laudantium dolores. Dicta quia est nostrum error ut magni dolorem.", userName: 'Marisa Kessler', bakeryName: 'b/bred', timePosted: 'Fri Jul 13 2018 04:38:21 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -31, commentsCount: 49, postType: 'text', postText: `Veritatis quisquam et et consectetur ab dolor. Autem atque expedita cum nulla et maiores ipsa ratione voluptates. Sunt cumque aut pariatur. Eveniet aut qui officia reprehenderit qui ab. Tempore rem autem ea debitis ex fugit neque qui. Atque eaque iure.

Nihil magnam quo alias ut ea officia. Officia necessitatibus voluptatem labore quia ipsa optio corrupti. Autem iusto excepturi est adipisci et.

Excepturi id deleniti ea pariatur quis aut sed non optio. Ex neque est pariatur expedita aliquam excepturi dolore. Commodi temporibus accusamus et ad labore et mollitia assumenda id.`, imageURL: null, postTitle: "Quia ipsam eos sequi omnis dolores minima ea ullam aliquid. Error inventore possimus ut perspiciatis dolor quibusdam non fuga eos. Quos non aut quo minima. Autem vero ut sit aspernatur. Velit eveniet nesciunt ratione aliquam. Quae molestiae quisquam ullam.", userName: 'Davon Luettgen', bakeryName: 'b/wholeWheat', timePosted: 'Mon Jul 16 2018 10:01:26 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 88, commentsCount: 139, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (935).jpg', postTitle: "Dignissimos earum velit maiores excepturi sequi id dolor reiciendis. Vitae inventore reprehenderit. Nisi non neque natus repudiandae excepturi incidunt. Quas voluptatibus excepturi. Alias consequatur quasi est incidunt maiores beatae.", userName: 'Gus Stoltenberg', bakeryName: 'b/catBread', timePosted: 'Sun Jun 02 2019 13:31:20 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 129, commentsCount: 75, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (988).jpg', postTitle: "Odio error magnam odio ad itaque vel quia sit quisquam. Et quasi ducimus quaerat magni vitae aliquid corrupti non. Non sunt hic enim esse doloribus non nihil.", userName: 'Fleta Frami I', bakeryName: 'b/Sourdough', timePosted: 'Wed Mar 13 2019 06:06:53 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -83, commentsCount: 13, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (552).jpg', postTitle: "Libero quod dolor excepturi sed aut quia fugiat. Nobis voluptas ut ut laudantium sint itaque odio dicta quaerat. Fugit tempora esse. Tenetur dolorum ea dolorem assumenda. Veritatis itaque aliquid qui dolore. Iusto et deserunt illo totam magni adipisci est assumenda.", userName: 'Marcel Kling', bakeryName: 'b/JudgeBredd', timePosted: 'Sat Apr 13 2019 09:26:47 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -72, commentsCount: 115, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (543).jpg', postTitle: "Nostrum saepe quia ea. Modi maxime consequatur tenetur dicta a dolorem eum. Non nulla accusantium tenetur sed numquam consequatur doloremque illum asperiores.", userName: 'Dr. Anabel Volkman', bakeryName: 'b/JudgeBredd', timePosted: 'Tue Nov 06 2018 09:41:31 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: -16, commentsCount: 219, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (776).jpg', postTitle: "At pariatur sed ipsam sit tenetur repellendus libero non voluptates. Ut recusandae adipisci debitis quae aut perspiciatis tenetur optio. Beatae cumque voluptas dolores ratione ut. Tempore nisi ipsam.", userName: 'Clotilde Harvey', bakeryName: 'b/wholeWheat', timePosted: 'Thu Mar 14 2019 16:42:28 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -23, commentsCount: 10, postType: 'text', postText: `Repellendus ea omnis qui qui. Ut magnam modi dignissimos aut molestias quia. Doloremque maxime ut aliquam laboriosam beatae quo dolore numquam. Temporibus saepe omnis ea delectus expedita mollitia.

Esse at accusantium est consectetur. Nihil est facere magnam laborum quis hic laudantium. Esse et qui ut excepturi accusantium nemo est. Enim ut in quaerat. Est recusandae doloremque molestias.

At delectus dignissimos et debitis cumque. Tempore sequi consectetur. Fugiat aut porro numquam quo eveniet id laudantium culpa. Ducimus magni voluptatum.`, imageURL: null, postTitle: "Enim odio ratione quia atque. Consequatur in et qui velit. Adipisci cumque accusantium voluptatum accusamus porro quidem culpa et. Quam odio odio placeat similique non expedita.", userName: 'Piper Grady', bakeryName: 'b/wholeWheat', timePosted: 'Wed Aug 29 2018 15:23:05 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 56, commentsCount: 135, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (501).jpg', postTitle: "Sed aut dolor. Et pariatur labore est animi facere fuga. Ducimus consectetur ab.", userName: 'Sophia Schmeler', bakeryName: 'b/Sourdough', timePosted: 'Thu Jul 12 2018 16:49:59 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 156, commentsCount: 59, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (986).jpg', postTitle: "Dolorum sed ut voluptates modi. Animi eaque exercitationem non est. Id libero eligendi autem pariatur non sed porro voluptas. Illum quibusdam magnam ullam sapiente veniam inventore minus error aliquam. Aut magni sit culpa quia sit iusto dolore.", userName: 'Miss Pearl Pfeffer', bakeryName: 'b/Sourdough', timePosted: 'Sun Sep 23 2018 17:38:21 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -61, commentsCount: 28, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (903).jpg', postTitle: "Aspernatur non tempora voluptatem ut et illum natus in. Sunt at nulla dolores voluptatum.", userName: 'Marc Abbott', bakeryName: 'b/wholeWheat', timePosted: 'Tue Sep 18 2018 06:14:13 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -64, commentsCount: 178, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (773).jpg', postTitle: "Culpa accusamus enim occaecati quo qui. Cumque iure modi eos. Voluptatem quasi ut omnis et sit ut quia optio. Natus repellat non.", userName: 'Mrs. Asha Ullrich', bakeryName: 'b/catBread', timePosted: 'Wed Dec 12 2018 22:36:11 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: -74, commentsCount: 13, postType: 'text', postText: `Velit velit quae amet omnis ipsum nulla facere animi voluptas. Laboriosam aspernatur soluta ad sed non cumque. Vel ducimus necessitatibus aperiam maxime iure exercitationem. Corporis voluptas non dolor saepe dolore amet. Excepturi adipisci at sunt non.

Ducimus quas eos voluptatem. Nobis impedit ratione quis aut et voluptatum aut. Et consequatur sed beatae nam maxime repellendus eius nihil. Libero labore in consequuntur ab earum itaque nemo aut.

Amet et amet error possimus officia odit quae neque. Modi culpa et voluptatum quo et. Error repellendus et soluta saepe saepe voluptatem libero. Dolor pariatur cupiditate sed nostrum assumenda odit beatae saepe dolores. Explicabo vel cum fugiat consequatur corporis enim vel. Laborum qui eius accusamus est quia non sint.`, imageURL: null, postTitle: "Est voluptatum magni optio quos hic maxime magni. Vero sit minus voluptas occaecati reiciendis officiis. Ut iure odio iure. Consequatur adipisci dolores cupiditate dolores incidunt eos iusto vero. Sunt ab quia incidunt voluptate excepturi veniam.", userName: 'Bill Russel', bakeryName: 'b/bred', timePosted: 'Fri Oct 26 2018 03:42:52 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 58, commentsCount: 11, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (586).jpg', postTitle: "Ipsam quo quis quia ipsum. Cum animi officia hic.", userName: 'Jada Goyette', bakeryName: 'b/Sourdough', timePosted: 'Fri Feb 08 2019 09:26:18 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: 135, commentsCount: 197, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (772).jpg', postTitle: "Doloribus eveniet libero est beatae sunt excepturi illo. Ut et et alias aut quis et assumenda odio aut. Iusto neque impedit sit impedit facilis. Quidem necessitatibus exercitationem labore praesentium. Iure quibusdam nemo nostrum atque quidem inventore deserunt enim.", userName: 'Beau Weber', bakeryName: 'b/JudgeBredd', timePosted: 'Mon Apr 08 2019 06:41:35 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -1, commentsCount: 7, postType: 'text', postText: `Commodi qui molestiae eos at eos quod. Qui hic aperiam similique non aut numquam. Perspiciatis quos quis qui nobis tempore eum. Voluptatem eligendi consequatur quae velit sit suscipit.

Veritatis alias eveniet optio voluptatum est. Nulla est qui et. Ad saepe recusandae neque. Delectus omnis labore odio.

Esse et nemo amet tenetur est. Et suscipit ratione quis quibusdam impedit qui tempora. Explicabo sunt delectus laborum dolorem voluptatem placeat vero. Consequuntur voluptatem doloremque voluptatem omnis est consequatur dolores ut. Corrupti repellendus fuga ducimus alias dicta est soluta dicta ipsa.`, imageURL: null, postTitle: "Facilis non dicta tempora maxime quos. Harum necessitatibus quasi in deleniti voluptas consequatur officia dolore nisi.", userName: 'Katlynn Skiles', bakeryName: 'b/wholeWheat', timePosted: 'Thu May 30 2019 04:22:39 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 59, commentsCount: 173, postType: 'text', postText: `Totam voluptatem est consequuntur non quo. Aut beatae perferendis et sint dolor consequatur. Recusandae fugit numquam adipisci voluptatem. Iure quas possimus temporibus qui vel cupiditate nihil.

Mollitia necessitatibus veniam ullam eum omnis corrupti perspiciatis et doloremque. Consectetur et velit ab quis dicta optio laborum dolores natus. Quo voluptatum quam et voluptatem sapiente adipisci. Vel et facere dolor ratione.

Vitae sit dolores. Ipsam quibusdam officia. Officia quia facere eos sed minus qui quo similique assumenda. Ipsum dolores et ut qui rerum voluptatem omnis blanditiis fuga.`, imageURL: null, postTitle: "Sint blanditiis amet suscipit eum ut et. Aut cupiditate numquam sed quia voluptatibus. Molestiae fuga reiciendis maiores dolor non consectetur.", userName: 'Nelda Heaney', bakeryName: 'b/JudgeBredd', timePosted: 'Sat Oct 13 2018 07:38:07 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 206, commentsCount: 24, postType: 'text', postText: `Maiores a quidem minus eligendi deserunt vel laborum. Repellat et aspernatur ut. Nihil fuga quia laborum ut quidem sit aut non.

Id aperiam cupiditate dignissimos. Sit voluptatem nihil maxime. Assumenda porro illum voluptas nostrum iusto sed odit est ex. Officia ipsam et dolores.

Et non possimus sequi. Qui explicabo beatae dolor error voluptate. Nulla sed impedit omnis est fugiat architecto non hic.`, imageURL: null, postTitle: "Dignissimos et rerum magnam ratione. Recusandae placeat nihil delectus aliquam sunt. Perferendis magnam impedit in. Quo officia quaerat qui voluptatibus provident rerum illum impedit. Nobis sed animi et ratione.", userName: 'Brice Dibbert', bakeryName: 'b/JudgeBredd', timePosted: 'Mon Feb 04 2019 08:35:11 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: -45, commentsCount: 0, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (650).jpg', postTitle: "Incidunt libero qui harum laudantium. Eius ducimus nobis ut nostrum quaerat.", userName: 'Kendrick Huel', bakeryName: 'b/wholeWheat', timePosted: 'Tue Aug 21 2018 01:18:46 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 184, commentsCount: 68, postType: 'text', postText: `Assumenda beatae non nisi eum dolores quam qui ut. Saepe perferendis consequatur ipsum est enim autem cumque. Dolores consequatur laboriosam fugit dolorem voluptas in voluptas.

Eaque voluptatum sapiente quaerat vel sit. Sapiente minus ut consequuntur. Neque voluptas consequatur tempora eum quos qui corporis quasi illum.

Repudiandae dolorem aut quidem. Quasi et qui ut totam molestiae deleniti exercitationem. Dolore tempora eos aliquam nesciunt. At quos repellendus recusandae blanditiis reprehenderit. Officia est autem voluptatum natus harum quia harum dolores molestiae.`, imageURL: null, postTitle: "Sed dolorem id laboriosam temporibus aut sit aliquid porro. Voluptatibus et debitis illum quidem est nobis aliquam repellendus.", userName: 'Julie Kassulke', bakeryName: 'b/JudgeBredd', timePosted: 'Fri Jan 04 2019 22:51:33 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: -82, commentsCount: 64, postType: 'text', postText: `Ipsa qui magni sit reprehenderit nemo voluptas. Commodi animi nostrum unde rerum alias porro eligendi illo. Voluptatum ut voluptatibus. Omnis dolorem omnis sunt laborum voluptatem doloremque. Dolore qui cumque eveniet nesciunt minima nostrum quidem. Corrupti magnam temporibus sapiente aut consequuntur explicabo odit.

Sint libero maiores dicta pariatur soluta eos. Maiores minus voluptatem similique voluptatibus et doloribus sit possimus. Exercitationem omnis vel excepturi ea voluptatem. Exercitationem provident quo necessitatibus et. Maiores id ut repudiandae cum ab.

Occaecati et eos. Deleniti consequatur esse quo consectetur odio ut omnis est libero. Asperiores rerum velit.`, imageURL: null, postTitle: "Et corrupti consequatur velit excepturi asperiores eum qui. Voluptas a eligendi quia veniam eaque impedit distinctio aliquam nostrum. Voluptatum sed corporis ab et enim suscipit autem sapiente atque. Exercitationem est sunt sit quo sunt. Dicta voluptatem nesciunt voluptatibus qui quia praesentium suscipit. Magni suscipit ex.", userName: 'Titus Keeling', bakeryName: 'b/HoneyOat', timePosted: 'Thu May 09 2019 07:34:59 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -2, commentsCount: 163, postType: 'text', postText: `Sit voluptatem expedita voluptas et non excepturi. Suscipit itaque sunt doloribus blanditiis eius. Ipsum incidunt qui tenetur. Dolores beatae et velit neque eum. Voluptas voluptatem laborum est. Et et temporibus.

Ab voluptates quidem tempore. Sed perferendis voluptatem odio. Impedit aut et iure magni sed reiciendis. Nisi dolorum debitis ut esse quam et. Modi culpa numquam ipsa ut autem.

Esse voluptatem nostrum. Sit repellendus nobis cupiditate sit illum corrupti. Aut quae quod unde.`, imageURL: null, postTitle: "Libero et quae est quasi. Praesentium cupiditate dolore eos recusandae autem soluta illo. Eos excepturi sed eos non ducimus corrupti dolorum quaerat. Molestiae quae et accusamus quis. Corrupti deleniti autem voluptas hic saepe et. Mollitia ratione nemo recusandae est quaerat alias dolor.", userName: 'Mr. Chanelle Hoeger', bakeryName: 'b/bred', timePosted: 'Fri Sep 28 2018 13:47:37 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 126, commentsCount: 198, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (907).jpg', postTitle: "Expedita voluptatem voluptatem eos dolor inventore eum aliquid. Consequatur animi tempora provident enim consequuntur provident provident. Consequatur totam animi tempore. Pariatur consectetur provident architecto et debitis possimus quis.", userName: 'Dagmar Kunze', bakeryName: 'b/Sourdough', timePosted: 'Mon Aug 20 2018 07:31:11 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 132, commentsCount: 240, postType: 'text', postText: `Et accusamus alias expedita tempore velit culpa. Hic aut dolor. Deleniti eligendi sed officiis ducimus reiciendis dicta qui quia cum. Est quibusdam et quia beatae iusto consequuntur. Ipsam deserunt ducimus quam porro. Et harum et ut officiis quo.

Laborum quasi facere id amet. Aut nisi rem similique. Quis accusantium dolor. Itaque ut architecto odit sed nobis quia voluptate impedit ipsa. Laudantium aut quo temporibus quo perspiciatis cupiditate ducimus fuga.

Eos rerum id eos libero dignissimos odio. Adipisci qui ut mollitia repudiandae. Eius vel nobis.`, imageURL: null, postTitle: "Ut quo provident consequatur eius incidunt. Rem in ut.", userName: 'Luella DuBuque', bakeryName: 'b/HoneyOat', timePosted: 'Mon Feb 25 2019 16:09:30 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: 103, commentsCount: 115, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (832).jpg', postTitle: "Praesentium animi ea enim. Adipisci odio ut sit sed officia. Ratione quod laboriosam tempora incidunt. Esse consequatur optio ad.", userName: 'Rodolfo Johns', bakeryName: 'b/JudgeBredd', timePosted: 'Fri Jun 07 2019 09:14:24 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 129, commentsCount: 142, postType: 'text', postText: `Illo veniam sed fugit. Fugit est aut quasi dolores facere nobis facilis reprehenderit. Iusto non quia tempore est quaerat corrupti totam eius. Voluptas est molestiae nulla dolorem totam. Dolores necessitatibus rem. Quam consectetur aliquid tempore ex alias.

Nihil nihil ex excepturi animi iure harum libero ut natus. Labore nisi ut nostrum est. Sit nobis beatae voluptate quas et. Iure repudiandae occaecati.

Dicta magnam eum vel adipisci sint hic excepturi eveniet. Et aut nemo explicabo iure culpa molestiae quam. Aperiam qui qui ad. Quo aut qui.`, imageURL: null, postTitle: "Quia suscipit hic laboriosam rem nihil repellat commodi voluptatem aspernatur. Est odio voluptatem adipisci nesciunt non. Et incidunt qui aut. Et recusandae laboriosam ut facilis quidem possimus incidunt.", userName: 'Raphaelle Mraz', bakeryName: 'b/bred', timePosted: 'Mon Jun 25 2018 08:36:15 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -56, commentsCount: 23, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (901).jpg', postTitle: "Et voluptas est accusamus quia. Excepturi quaerat quaerat perferendis consequatur.", userName: 'Hester Stehr', bakeryName: 'b/wholeWheat', timePosted: 'Wed Oct 17 2018 15:59:25 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 36, commentsCount: 0, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (877).jpg', postTitle: "Enim non porro ea maiores voluptatem ducimus ad molestiae rem. Ullam iste in nostrum quisquam autem quisquam voluptatem quo est. Non sit maxime ut quaerat eligendi. Magni asperiores aut laboriosam reiciendis corporis minima deserunt. Itaque nemo accusantium occaecati magni nostrum id.", userName: 'Thalia Carroll', bakeryName: 'b/Sourdough', timePosted: 'Fri Jun 29 2018 01:04:59 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 164, commentsCount: 82, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (535).jpg', postTitle: "Ut aut asperiores velit cupiditate rerum est ex aut. Blanditiis qui repellat ipsum quam.", userName: 'David Sauer', bakeryName: 'b/catBread', timePosted: 'Wed Feb 20 2019 01:54:26 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: 33, commentsCount: 126, postType: 'text', postText: `Qui amet quae iusto neque aperiam a incidunt dolores. Accusantium quia dolorem. Illum sit culpa architecto dolores.

Ullam voluptate aut. Atque incidunt ut sint qui. Dignissimos quia voluptatem numquam dignissimos in. Animi recusandae odio assumenda rerum odit aliquam architecto.

Vero qui voluptatem. Est quae sit pariatur. Provident rerum id omnis porro. Dignissimos ut tenetur voluptas ullam nam commodi consequatur qui nisi. Aperiam praesentium qui. Ullam vitae beatae numquam in ratione eos quam.`, imageURL: null, postTitle: "Atque qui tempore velit beatae repudiandae. Possimus aliquid accusamus aut.", userName: 'Reagan Gleichner', bakeryName: 'b/JudgeBredd', timePosted: 'Fri Jul 20 2018 00:09:56 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -37, commentsCount: 148, postType: 'text', postText: `Dolorem qui sed ut. Sit possimus qui et eum repudiandae. Perspiciatis deleniti quasi qui provident quo aliquam reiciendis praesentium omnis. Expedita ea sint accusantium. Ut dolorum soluta dicta non necessitatibus suscipit deserunt. Corrupti est dignissimos.

Repudiandae ea in nihil. Fugit consequatur modi perspiciatis repellendus quos consequuntur tenetur. Exercitationem in similique expedita rerum officiis. Consequatur dolorem esse quia quos beatae sit. Cumque eligendi reprehenderit dolores sit possimus. Iusto ea sapiente quos tempore.

Nobis veniam qui fugit. Illum odio omnis deserunt. Ut distinctio impedit in libero doloremque.`, imageURL: null, postTitle: "Qui error aut magni. Ipsum maxime voluptatem vel sunt doloremque. Quisquam velit quia. Ex tempora voluptatibus omnis quasi neque est iste iure. Delectus quod eum odit.", userName: 'Oswald Kautzer', bakeryName: 'b/wholeWheat', timePosted: 'Mon Oct 08 2018 15:38:45 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -45, commentsCount: 117, postType: 'text', postText: `Ipsum nulla tenetur aperiam beatae sapiente et numquam aperiam. Rerum eius illum quae veritatis inventore vero. Ut sed harum architecto reprehenderit exercitationem eos ut. Eligendi culpa consequatur consequatur sed et.

Et ullam ullam. Temporibus iste doloribus rerum harum omnis dolorem alias quae. Rerum nam alias vel fuga. Nesciunt quas laudantium exercitationem ut sequi adipisci.

Blanditiis ipsa nesciunt incidunt corrupti corrupti unde quidem. Minus eos consequatur. Eaque et veniam quia optio amet. Rerum iste odio. Incidunt quis quis explicabo cupiditate laboriosam nihil rerum.`, imageURL: null, postTitle: "Ea rem pariatur animi et atque. Et reprehenderit sapiente tempora odio sunt possimus id doloremque. Quia veritatis iste maxime voluptas. Voluptatem molestiae magni. Quae minima velit explicabo a. Exercitationem laboriosam consectetur nihil sit esse temporibus quas nihil saepe.", userName: 'Sandrine Torphy', bakeryName: 'b/Sourdough', timePosted: 'Sat Jun 23 2018 05:18:05 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 24, commentsCount: 0, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (507).jpg', postTitle: "Harum laborum dolore et dignissimos eum quia vero non. Ipsam sed in.", userName: 'Elizabeth Adams', bakeryName: 'b/bred', timePosted: 'Fri Jul 06 2018 22:17:44 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -50, commentsCount: 4, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (812).jpg', postTitle: "Rerum doloribus nostrum. Esse consequatur quaerat temporibus fugit quibusdam ad.", userName: 'Ms. Sherman Beer', bakeryName: 'b/bred', timePosted: 'Sat Mar 02 2019 21:38:01 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: -94, commentsCount: 19, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (578).jpg', postTitle: "Nisi quo quas soluta aut cupiditate. Aut itaque at itaque qui ullam ducimus nulla eaque.", userName: 'Blanca Beatty', bakeryName: 'b/Sourdough', timePosted: 'Sat Mar 09 2019 18:39:07 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: 237, commentsCount: 0, postType: 'text', postText: `Id non blanditiis ducimus qui aspernatur. Aut nulla sed corporis et incidunt molestias. Voluptas consequatur odit non id omnis voluptates. Et molestiae qui a qui ab incidunt neque eius. Dicta dolor dolor sunt voluptas rem. Odio totam ut omnis similique sequi molestiae dolor ut.

Adipisci voluptatibus quas officia molestiae. Est laudantium pariatur nulla eligendi nostrum officia et. A itaque porro officiis ea.

Earum tempora aut vitae consequatur. Molestias debitis occaecati. Fugiat veritatis exercitationem error.`, imageURL: null, postTitle: "Officiis culpa nam saepe sed sint doloribus dignissimos ut. Rerum et vitae.", userName: 'Neva Rice IV', bakeryName: 'b/bred', timePosted: 'Sat Sep 08 2018 23:05:50 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -2, commentsCount: 185, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (563).jpg', postTitle: "Recusandae atque aut expedita temporibus enim et. Praesentium culpa iure provident totam similique. Nemo distinctio recusandae quaerat corrupti ut est voluptas id. Fugit repudiandae doloribus quidem. Soluta illum fuga repudiandae non. Possimus ducimus omnis alias debitis nobis dolorum cumque.", userName: 'Ms. Hannah Kub', bakeryName: 'b/Sourdough', timePosted: 'Mon Nov 19 2018 12:19:42 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: 172, commentsCount: 154, postType: 'text', postText: `Suscipit ab a est laboriosam a iusto. Amet aperiam nisi earum esse. Voluptas ipsam qui ut non sunt. Fugit ex veniam adipisci sit occaecati. Voluptate tenetur officia expedita quia quo nostrum nulla.

Accusamus vel odit facere beatae repellendus ut ut. Aut corporis rem. Corrupti minima quidem. Et possimus quis voluptatem dolor laudantium et et in laborum. Fugit voluptatem occaecati est culpa.

Similique non est quia impedit cupiditate. Et consequatur tempore aliquam magnam possimus dolorem ullam omnis est. Voluptatem voluptatem adipisci consequatur dolorem est eos nulla. Voluptatem repellendus beatae aut quasi. Ipsam quo dolores voluptas unde impedit quis qui repudiandae qui. Labore similique hic dolorum ex dolorem fuga nam ad.`, imageURL: null, postTitle: "Unde totam ipsa minima. Doloribus repellat et.", userName: 'Rodrigo Bartoletti V', bakeryName: 'b/bred', timePosted: 'Sun Mar 31 2019 10:40:28 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -77, commentsCount: 110, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (942).jpg', postTitle: "Dolorem dolorem sed esse et ut cum qui accusantium. Explicabo accusamus vel ex optio quod ut molestiae.", userName: 'Mr. Ashley Schulist', bakeryName: 'b/JudgeBredd', timePosted: 'Mon Nov 26 2018 19:32:31 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: 112, commentsCount: 119, postType: 'text', postText: `Temporibus facilis inventore adipisci. Incidunt voluptas nihil accusamus. Id perspiciatis et. Corrupti esse aut quae adipisci ea quos nihil assumenda. Ut nam ab ea ab.

Rerum iure pariatur aliquid. Reprehenderit quisquam adipisci veritatis ab qui ut incidunt mollitia odio. Est officia nemo explicabo ex vitae velit accusamus in sit. Suscipit et quaerat quae saepe expedita quasi illo deserunt.

Exercitationem voluptas molestiae harum nulla possimus excepturi et. Modi quo sed amet velit porro dolorum debitis beatae. Culpa rem nihil non et cumque sit aliquam quas. Vel aperiam id provident. Omnis sit numquam deserunt sint vel repellat laboriosam. Suscipit facilis perspiciatis tempore.`, imageURL: null, postTitle: "Quis voluptatibus quas deleniti aut qui exercitationem odio dicta illo. Sapiente corrupti maxime labore. Tempora autem dignissimos. Laborum quidem assumenda quaerat laborum consequuntur aliquam a iste id. Est tempore deleniti dignissimos incidunt.", userName: 'Noemy Huels', bakeryName: 'b/JudgeBredd', timePosted: 'Sat Oct 13 2018 23:49:13 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -27, commentsCount: 71, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (583).jpg', postTitle: "Impedit et temporibus voluptatem velit recusandae iste ut totam beatae. Voluptas officia accusantium aliquid quia eum quia animi non cupiditate. Rerum ipsum natus hic suscipit autem saepe aperiam necessitatibus impedit. Voluptatem officiis ut ut earum distinctio facere. Ad vel ullam animi. Voluptate aperiam iusto sapiente autem.", userName: 'Josiane Bradtke', bakeryName: 'b/Sourdough', timePosted: 'Tue Jun 11 2019 17:34:41 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -9, commentsCount: 190, postType: 'text', postText: `Itaque doloribus expedita. Dolorem inventore necessitatibus qui necessitatibus harum ea eius. Debitis ea corrupti ad nulla nulla molestias pariatur. Modi delectus pariatur sint. Impedit eveniet cupiditate iure placeat quo distinctio mollitia.

Accusamus enim sed perferendis architecto tempore tenetur asperiores. Sint sint neque. Tempore nihil est aut est quia sed magni odio.

Qui temporibus natus minima et consequatur eaque. Consectetur a repellendus aut totam et dolor non consequatur voluptates. Odit quas placeat vero voluptatem dolore veritatis dolorem placeat culpa. Quia officiis officiis inventore ex qui hic et voluptatem.`, imageURL: null, postTitle: "Qui in numquam. Quo non est ut facere in nam. Omnis atque adipisci perferendis non iste corporis.", userName: 'Mollie Goodwin Jr.', bakeryName: 'b/HoneyOat', timePosted: 'Tue Sep 11 2018 04:05:35 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -22, commentsCount: 112, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (864).jpg', postTitle: "Et id et. Molestiae quis facere eligendi possimus aut harum unde ipsa omnis. Molestiae cum accusantium sunt repudiandae molestias exercitationem consequatur in. Laboriosam itaque omnis iste fugiat necessitatibus est enim.", userName: 'Miss Vena Hyatt', bakeryName: 'b/bred', timePosted: 'Thu Dec 13 2018 11:30:01 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: -100, commentsCount: 185, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (705).jpg', postTitle: "Velit suscipit magnam iste omnis velit et incidunt perspiciatis. Et aut tenetur aut molestiae recusandae et doloribus sed et. Rerum ut doloremque sequi repudiandae porro. Et qui quaerat nihil officia qui aut sit soluta. Earum autem aut ut dolores vitae et. Tempore veniam eos ut odit aut.", userName: 'Derrick Reinger V', bakeryName: 'b/JudgeBredd', timePosted: 'Wed Jun 12 2019 05:25:45 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 26, commentsCount: 247, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (844).jpg', postTitle: "Error rerum officia quia repellat nihil. Consequatur aut nulla aut ut exercitationem. Suscipit minima libero a ut quas. Porro ab doloremque perspiciatis.", userName: 'Ava Schumm Jr.', bakeryName: 'b/wholeWheat', timePosted: 'Fri Jun 14 2019 00:55:42 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 217, commentsCount: 23, postType: 'text', postText: `Dolorum cum corrupti tenetur sed. Magnam inventore id molestias mollitia deserunt quos molestias cum ex. Possimus consequatur quaerat dolorum sit qui et rem natus. Et qui ut.

Non ab soluta ab tenetur quisquam aut sunt id. Voluptatem minus in alias. Vitae dolor numquam. Enim quo et inventore rerum quas omnis. Nihil eveniet exercitationem quia provident nihil aliquid.

Asperiores temporibus odio ut voluptas voluptas. Tempora est assumenda eius sed sit vero sit. Eveniet reiciendis explicabo dolore. Velit inventore ut enim totam non repellat eos voluptatem. Sed earum deserunt dignissimos dolores quis sed. Quisquam dignissimos quo repellendus omnis saepe sed qui repellat et.`, imageURL: null, postTitle: "Facere culpa recusandae perspiciatis. Inventore dolores blanditiis et deserunt hic sint.", userName: 'Annie Witting', bakeryName: 'b/Sourdough', timePosted: 'Mon Oct 22 2018 01:07:01 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -73, commentsCount: 221, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (906).jpg', postTitle: "Quos perspiciatis debitis velit. Asperiores amet sit debitis rerum accusantium consequuntur est. Quis voluptatem id. Voluptas placeat et et et fugit qui necessitatibus veritatis. Repellendus eius ea. Consequatur ut quasi voluptatem quasi debitis occaecati.", userName: 'Yvonne Lesch', bakeryName: 'b/catBread', timePosted: 'Wed Mar 20 2019 06:19:07 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -12, commentsCount: 210, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (635).jpg', postTitle: "Praesentium nostrum occaecati rerum dicta perspiciatis dignissimos. Totam eum est.", userName: 'Drake Heidenreich', bakeryName: 'b/wholeWheat', timePosted: 'Sat Jan 19 2019 03:25:30 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: -75, commentsCount: 23, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (667).jpg', postTitle: "Eos vero adipisci ea autem quasi voluptate et voluptatem. Eos atque voluptatibus est dolor doloribus voluptatem sed. In est accusantium excepturi dolores.", userName: 'Eloise Wisoky', bakeryName: 'b/JudgeBredd', timePosted: 'Tue Sep 11 2018 09:49:42 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -84, commentsCount: 143, postType: 'text', postText: `Qui qui dolorem iure provident quae dolor. Accusantium error adipisci est et nemo deserunt corrupti eos. Omnis nemo ipsa. Et fuga reiciendis est inventore quia et. Voluptas recusandae quia dolores. Neque velit sit quas doloribus omnis non soluta omnis asperiores.

Repellat expedita qui ut quis labore molestiae non nobis omnis. Quibusdam veritatis porro porro ut nostrum. Impedit reprehenderit asperiores quidem est omnis aspernatur eligendi corporis illum. Omnis fuga voluptas.

Vel quod architecto tempora veritatis assumenda. Et est fugit repellat perferendis ipsum. Quidem consequatur et. Esse exercitationem rerum velit delectus qui. Dolor veniam doloremque et rem et. Accusantium nihil occaecati.`, imageURL: null, postTitle: "Mollitia eos expedita optio id repudiandae similique dicta natus. Et dolorem eos aut. Optio exercitationem qui porro et molestiae aut doloribus. Nobis eum totam ullam voluptatem cumque. Incidunt magnam aliquid explicabo ipsam maiores id.", userName: 'Mr. Corine Johnston', bakeryName: 'b/Sourdough', timePosted: 'Sun May 05 2019 07:00:33 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 220, commentsCount: 92, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (519).jpg', postTitle: "Aut asperiores dolor. Accusantium sed exercitationem tempora quod aut rerum et quia ullam.", userName: 'Dorris Buckridge', bakeryName: 'b/HoneyOat', timePosted: 'Wed Apr 03 2019 02:55:54 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 224, commentsCount: 130, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (823).jpg', postTitle: "Sapiente aspernatur praesentium sunt. Dolor incidunt ut aut vel.", userName: 'Marvin Dicki DVM', bakeryName: 'b/HoneyOat', timePosted: 'Sat Feb 16 2019 22:34:18 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: 94, commentsCount: 238, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (689).jpg', postTitle: "Consectetur ullam sunt pariatur aliquam. Quidem aut ducimus. Est atque culpa et odio earum ut vero quod ullam.", userName: 'Laney Rice', bakeryName: 'b/wholeWheat', timePosted: 'Wed Sep 12 2018 09:47:38 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 159, commentsCount: 88, postType: 'text', postText: `Maiores magnam corporis recusandae consequatur ducimus omnis recusandae quis voluptates. Est vel neque nemo eveniet nihil aut officia repudiandae. Quam ullam explicabo voluptatem officia sapiente quia unde magni. Earum omnis officiis.

Voluptas dignissimos qui harum voluptatem culpa. Recusandae est a et non ullam. Sapiente blanditiis vero voluptatem et molestiae hic. Sit id aut molestiae accusantium placeat amet odio sit. Consequatur id facere labore id. Sed quas aspernatur sequi eos quos quisquam cupiditate aut.

Consequatur debitis rerum et nobis. In expedita quia praesentium nobis a. Saepe quia nulla quis.`, imageURL: null, postTitle: "Quis velit omnis facere ut tempore. Minima et voluptatibus neque in ut magni molestias. Ab et temporibus enim odio ab. Sunt odit laborum beatae nisi eligendi culpa sunt possimus quo. Sed consequatur sit commodi qui aut. Dicta eligendi et voluptatem commodi voluptatem reprehenderit voluptas sed ut.", userName: 'Dr. Shany Leffler', bakeryName: 'b/Sourdough', timePosted: 'Wed Jan 23 2019 19:30:51 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: -16, commentsCount: 192, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (740).jpg', postTitle: "Praesentium consequatur fugit corporis sit sint molestiae. Blanditiis amet fugit. Maxime odit aspernatur tempore. Doloribus voluptate voluptas cupiditate. Aut cupiditate est doloribus iste totam soluta ut soluta id.", userName: 'Buck Schiller', bakeryName: 'b/HoneyOat', timePosted: 'Sat Aug 25 2018 22:07:32 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 144, commentsCount: 40, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (785).jpg', postTitle: "Ipsam ducimus ducimus quam. Laboriosam rerum dolores maxime rem laboriosam. Non veniam ab qui eligendi totam mollitia. Et blanditiis est ea vel facere. Magnam quia adipisci consequatur et ratione unde. Ad dolorem quae tempora minus voluptatem quia neque porro.", userName: 'Claud Pouros III', bakeryName: 'b/catBread', timePosted: 'Sat Dec 01 2018 23:07:15 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: -80, commentsCount: 84, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (647).jpg', postTitle: "Sit corrupti est magni maiores voluptas pariatur adipisci dolorem reiciendis. Voluptatem iusto ab officiis soluta et corrupti sit ex incidunt. Temporibus itaque ex ad possimus voluptates distinctio soluta velit. Commodi repudiandae animi suscipit. Esse consequatur dolorum odio dignissimos perspiciatis.", userName: 'Valentin Flatley', bakeryName: 'b/wholeWheat', timePosted: 'Sun Sep 23 2018 23:23:57 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -85, commentsCount: 74, postType: 'text', postText: `Voluptatem culpa earum temporibus iste. Laboriosam nihil totam et. Consequatur vel quia eius quis atque non voluptas. Nulla vel aliquid et labore numquam praesentium est repellendus. Occaecati qui eligendi aut.

Culpa ex occaecati asperiores quidem dolores repudiandae id. Velit repellat sint molestiae quae dolorem. Magnam consequatur quaerat enim autem quasi omnis.

Autem molestiae neque et. Voluptas et qui quia. Enim ut debitis doloremque in iusto. Nam quas ut qui delectus.`, imageURL: null, postTitle: "Ut laudantium quasi omnis ut. Recusandae corporis et adipisci. Quidem consequatur tempora officia commodi iure. Corrupti beatae eos. Exercitationem quia natus qui.", userName: 'Bertha Sporer', bakeryName: 'b/Sourdough', timePosted: 'Sat Apr 27 2019 06:17:19 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 151, commentsCount: 69, postType: 'text', postText: `Voluptatem eos fuga molestiae praesentium. Beatae molestias delectus ut qui. Totam fugit facere tenetur quidem eius ut possimus. Quo repudiandae quam est aut quia minus modi nihil. Fugiat neque vero est sit. Quos dolorum voluptas commodi nesciunt delectus libero quis nobis.

Dicta occaecati quaerat qui sed et suscipit. Facere ea at qui. Voluptas commodi aut commodi est sint veritatis omnis. Sed enim eos consequuntur accusantium voluptatum sit molestiae fugiat. Impedit et aut.

Pariatur dolor dolores exercitationem quis dolores eius. Dicta aut pariatur velit ut doloremque sed molestiae est molestiae. Rerum natus earum ullam est sed possimus aut soluta. Blanditiis nesciunt earum enim. Rerum est fuga sint at ex.`, imageURL: null, postTitle: "Cupiditate eos aut. Ex eius excepturi rerum sunt neque voluptas. Inventore numquam quia non.", userName: 'Anibal Rodriguez', bakeryName: 'b/JudgeBredd', timePosted: 'Wed Oct 17 2018 16:41:39 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 64, commentsCount: 119, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (760).jpg', postTitle: "Iure odio aut similique. Neque similique rerum consequatur laboriosam deleniti. Autem rerum laboriosam a rem iure. Ut facere non magni fuga.", userName: 'Charley Corkery', bakeryName: 'b/Sourdough', timePosted: 'Wed Jun 20 2018 23:51:43 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 29, commentsCount: 227, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (852).jpg', postTitle: "Ipsa blanditiis enim consequatur iusto at numquam soluta et. Harum quod ut beatae ea optio. Voluptas quam itaque enim aut id. Delectus qui nisi magni debitis possimus. Non rerum ullam totam recusandae.", userName: 'Jerad Deckow I', bakeryName: 'b/HoneyOat', timePosted: 'Sun Apr 28 2019 03:26:44 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -61, commentsCount: 112, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (905).jpg', postTitle: "Necessitatibus doloribus sed voluptatem. Eius nisi accusantium perferendis quas suscipit incidunt cumque.", userName: 'Perry Anderson Sr.', bakeryName: 'b/catBread', timePosted: 'Sun Jun 16 2019 15:14:03 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -17, commentsCount: 81, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (531).jpg', postTitle: "Velit quod inventore possimus iure aliquid qui. Temporibus harum voluptate autem architecto. Omnis harum quos laborum quibusdam. Omnis earum vero earum et illum eum voluptate. Tenetur qui non tempore assumenda maxime molestiae architecto accusamus. Maxime tenetur ab veniam saepe incidunt dignissimos.", userName: 'Darrel OReilly', bakeryName: 'b/wholeWheat', timePosted: 'Wed Jan 23 2019 15:16:47 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: -43, commentsCount: 177, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (513).jpg', postTitle: "Voluptatem tempore et blanditiis labore non impedit. Consequatur molestias laborum saepe aperiam optio vel voluptatibus consectetur. Sunt dicta iste. Dicta dicta in laudantium consequuntur vero ut. Deserunt repellat facere optio. Ullam enim vel est aut ratione excepturi excepturi.", userName: 'Reggie Brekke', bakeryName: 'b/wholeWheat', timePosted: 'Mon Apr 22 2019 07:11:27 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -8, commentsCount: 16, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (751).jpg', postTitle: "Neque quae nisi et repellendus. Beatae tenetur magni qui repellat autem laboriosam occaecati sint eius. Sint sunt quae sit. Delectus quae illum ut iste maxime et dicta nam. Corporis et molestiae nulla laboriosam. Eum numquam illum repellendus est.", userName: 'Rebeka Halvorson', bakeryName: 'b/JudgeBredd', timePosted: 'Wed May 15 2019 12:20:00 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 245, commentsCount: 180, postType: 'text', postText: `Laborum architecto ab illum saepe dicta quia. Atque eos sed quod ullam. Aut fuga consequuntur fugit laboriosam corrupti placeat. Quasi quo asperiores et incidunt molestias.

Consectetur voluptatem reiciendis tempore illo est deserunt. Excepturi commodi molestias. Ut odio distinctio ad dignissimos id et aspernatur. Neque itaque sed optio quibusdam cupiditate. Tempora consequatur officiis corporis distinctio expedita. Laboriosam enim et qui ut odit.

Voluptas suscipit sit voluptatem. Autem pariatur dolorum mollitia voluptatem cupiditate odio. Quo reprehenderit ut nulla et dolorem omnis eligendi. Incidunt consectetur non ipsa similique ab quia. Delectus necessitatibus neque autem excepturi.`, imageURL: null, postTitle: "Quia et quisquam incidunt ut quasi nemo. Aut possimus consectetur fugiat magni et. Est porro omnis officiis dolores. Ab omnis omnis voluptatem aut inventore illo. Optio et nobis impedit.", userName: 'Clementina Boyle Jr.', bakeryName: 'b/JudgeBredd', timePosted: 'Fri Apr 26 2019 22:18:12 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 100, commentsCount: 65, postType: 'text', postText: `Enim omnis et eos esse dolor et rem. Aut et sunt. Quibusdam libero eius amet ipsam. Debitis reiciendis nobis. Enim ea nemo est rem distinctio vitae.

Facere qui ipsam optio excepturi incidunt inventore omnis. Doloribus incidunt iure. Ut possimus mollitia quis atque soluta consequuntur quis rem. Rerum dolorem et quo accusantium placeat qui.

Tempore deleniti facere modi aut ut repudiandae id. Explicabo vel vitae et molestias tenetur. Ut quod voluptates nesciunt voluptate saepe. Quaerat explicabo consequatur et dolores qui optio.`, imageURL: null, postTitle: "Deleniti voluptatem iure quod quidem et nulla recusandae. Accusamus qui inventore dolores qui minus libero excepturi laborum a. Molestiae suscipit debitis saepe qui praesentium et laudantium earum. Neque dolores ea sit deleniti voluptatem molestias in tempora at.", userName: 'Donny Grant', bakeryName: 'b/JudgeBredd', timePosted: 'Sun Mar 24 2019 00:58:45 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 162, commentsCount: 119, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (555).jpg', postTitle: "Nihil ut natus aut recusandae distinctio similique eveniet excepturi praesentium. Facilis dolor magnam sint commodi dolores voluptas consequatur aliquid. Quis aperiam id est odit hic repellendus.", userName: 'Sabrina Lebsack II', bakeryName: 'b/wholeWheat', timePosted: 'Thu Apr 04 2019 03:22:24 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 145, commentsCount: 173, postType: 'text', postText: `Quas quas laborum dolore et sapiente natus. Eveniet similique ut doloribus exercitationem et saepe. In consequatur iure et cumque est asperiores consequatur.

Nesciunt cupiditate voluptates. Ipsam consequatur soluta quos. Perferendis deserunt laudantium et. Modi eos ut voluptatibus incidunt. Minus adipisci impedit voluptatum. Sint soluta quod totam qui.

Reiciendis velit et recusandae dolor dolorem aperiam. Eligendi qui ut debitis optio quidem. Et eum hic animi praesentium.`, imageURL: null, postTitle: "Ut earum praesentium earum quis quia nesciunt. Vero laboriosam quidem vel sunt possimus. Id at magnam odit ut deserunt quasi suscipit. Ut possimus vero rem delectus et eum eos. Numquam aperiam saepe tempore.", userName: 'Una Pouros', bakeryName: 'b/JudgeBredd', timePosted: 'Fri Jun 07 2019 06:35:45 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 228, commentsCount: 241, postType: 'text', postText: `Earum eaque quidem non. Doloremque aut quia et aspernatur. Optio ratione fugit dolor ut quisquam aut sed. A voluptatum maxime voluptate ratione ut et inventore.

Repudiandae quos laborum alias magnam id sapiente. Sequi qui ipsum et maxime deleniti consequuntur molestias illum voluptatibus. Nesciunt rem laboriosam qui aut ipsum eligendi tempora ipsa.

Aut velit ut eum voluptatem aliquam maiores. Iste molestias quis ipsum non consequatur velit eligendi placeat vel. Iure et eligendi dicta doloribus aspernatur. Quia saepe illo doloribus nihil. Cumque officiis iure magnam vel autem dicta modi minima.`, imageURL: null, postTitle: "Dolorum qui ex et temporibus quod iusto voluptatibus ipsum. Ut iure autem dicta tempore saepe necessitatibus consequatur illo.", userName: 'Aiyana Flatley', bakeryName: 'b/HoneyOat', timePosted: 'Wed Oct 10 2018 04:06:11 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -94, commentsCount: 38, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (577).jpg', postTitle: "Excepturi nisi assumenda rerum et perspiciatis velit consequuntur. A labore voluptatibus. Quas et et consequatur suscipit voluptas asperiores quos assumenda mollitia. Dignissimos rerum in qui ipsum omnis veritatis. Natus quam dignissimos.", userName: 'Peggie Batz', bakeryName: 'b/HoneyOat', timePosted: 'Mon Dec 10 2018 00:31:11 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: -15, commentsCount: 119, postType: 'text', postText: `Debitis dolores ut culpa labore blanditiis. Ipsum sunt corporis sit amet voluptate eum quibusdam aliquid. Et aut aut corporis alias accusantium. Dolorem et illum suscipit dolorem dolore. Vel omnis quia id quo modi repellendus cupiditate harum necessitatibus.

Quas velit vitae et. Odit explicabo nihil maiores sit. Et natus sit laborum dolor earum quos rerum eum est. Possimus laborum rem aut omnis accusamus.

Animi aut facere et in ad esse. Quaerat iusto et vel ipsum officiis vitae. Itaque ea maiores natus accusamus quo sint quia sit. Ut aspernatur recusandae molestias qui. Nihil error numquam optio sit omnis reiciendis sed iste voluptas. Repellat ut laborum magni quisquam et.`, imageURL: null, postTitle: "Labore consequatur sit possimus deleniti voluptatibus nemo dolorum et eos. Omnis ut minima enim illo in. Sunt fugiat amet rerum ut fuga facilis. Et aliquam harum odit. Sed natus maxime sint officia ut. Facilis soluta est vel et.", userName: 'Eldred Wyman I', bakeryName: 'b/wholeWheat', timePosted: 'Tue Jan 01 2019 09:52:50 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: -37, commentsCount: 56, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (952).jpg', postTitle: "Rem necessitatibus quas quo et qui aut eius. Odit ducimus voluptatem illum modi nostrum. Sapiente sed rerum non in fugiat et maxime. Reiciendis magni amet. Maxime et autem consectetur enim et ipsa ab voluptate ipsa. Quis ipsam quod cumque esse consequatur delectus.", userName: 'Maurice Runolfsdottir', bakeryName: 'b/bred', timePosted: 'Thu Mar 21 2019 16:57:26 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -51, commentsCount: 3, postType: 'text', postText: `Et amet fugit debitis architecto. Et porro illum libero aliquam labore. Fugit laborum rerum iste odit sint. Natus delectus facere consequatur maxime sed. Fugiat unde labore inventore odit enim.

Quo saepe exercitationem. Quaerat quam fugit qui deserunt. Necessitatibus in ipsam numquam doloribus quae id vitae ipsa totam. Non quidem molestiae. Maiores qui nemo non qui beatae maxime placeat dolorum.

Velit est non. Sapiente placeat eius nesciunt et labore qui voluptates. Dolor laudantium autem voluptates nisi sapiente placeat aperiam. Nihil harum nostrum tempore eos est. Corporis nemo voluptatibus explicabo minus.`, imageURL: null, postTitle: "Sunt vel minus rem nesciunt qui similique laudantium voluptate. Nihil voluptates sunt temporibus natus saepe. Quia fuga expedita vel atque est et aliquam qui nulla. Saepe vel omnis amet accusamus eius ratione voluptatem. Nihil inventore nostrum fugiat ipsa.", userName: 'Marcella Yundt', bakeryName: 'b/JudgeBredd', timePosted: 'Wed Apr 17 2019 07:22:42 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 94, commentsCount: 163, postType: 'text', postText: `Quaerat aut non temporibus optio voluptas. Sint nisi sapiente sint quis molestiae vel reprehenderit qui id. Et laudantium qui impedit eveniet minima. Alias repellat placeat sint neque.

Voluptas qui eligendi quis minus tenetur. Illo dignissimos pariatur repellendus esse. Aliquid atque ea molestiae consequatur excepturi. Laborum placeat consequatur quae.

Laboriosam asperiores excepturi ducimus. Maxime necessitatibus culpa qui ipsum eos. Consequatur ratione corrupti voluptas qui autem laboriosam ut consequatur ratione. Aut repudiandae numquam eligendi voluptatibus. Sed tempora voluptatem assumenda.`, imageURL: null, postTitle: "Natus consequuntur ut optio voluptatum maxime aut delectus vel. Voluptas beatae et. Maiores a et sed sed reprehenderit suscipit ut illum est. Totam deleniti non laborum enim inventore eaque illo qui.", userName: 'Art Williamson', bakeryName: 'b/JudgeBredd', timePosted: 'Wed Aug 08 2018 19:43:06 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -14, commentsCount: 60, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (598).jpg', postTitle: "Velit adipisci aperiam molestiae ducimus ratione nisi. Maiores nostrum incidunt nulla. Necessitatibus dolores omnis qui doloribus molestias quia fugiat mollitia neque.", userName: 'Frieda Heathcote', bakeryName: 'b/wholeWheat', timePosted: 'Tue Jul 31 2018 05:02:10 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: 103, commentsCount: 165, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (814).jpg', postTitle: "Aut atque non minus cupiditate aut qui et alias. Omnis molestiae praesentium cumque omnis voluptatem. Quo ex et facilis.", userName: 'Caleigh Fritsch', bakeryName: 'b/Sourdough', timePosted: 'Fri Dec 07 2018 15:26:28 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: 168, commentsCount: 185, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (536).jpg', postTitle: "Amet blanditiis voluptas voluptatum sint quod quia consequuntur reiciendis aperiam. Quae ut facere quos suscipit. Delectus est voluptas. Provident commodi voluptas. Minima sed incidunt assumenda accusantium adipisci aliquid cupiditate.", userName: 'Virginia Schmidt', bakeryName: 'b/HoneyOat', timePosted: 'Sat Jul 07 2018 15:39:33 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -18, commentsCount: 25, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (808).jpg', postTitle: "Voluptatem cum alias veritatis inventore minus dolorem eum nihil. Minima voluptas omnis blanditiis qui necessitatibus aut illo ipsam quo. Repellat facilis ea aut autem facere excepturi. Ex quidem architecto occaecati. Eum ipsum occaecati nihil.", userName: 'Granville Moen', bakeryName: 'b/catBread', timePosted: 'Tue May 28 2019 19:39:15 GMT-0700 (Pacific Daylight Time)' },
  { sipzCount: -45, commentsCount: 196, postType: 'image', postText: null, imageURL: '../../src/assets/bread/bread (653).jpg', postTitle: "Sint et veritatis occaecati modi fugit magni. Sed at sit repellendus ut ea tempore ut. Omnis voluptatem odit.", userName: 'Tyrel Cummings', bakeryName: 'b/wholeWheat', timePosted: 'Tue Nov 20 2018 17:07:57 GMT-0800 (Pacific Standard Time)' },
  { sipzCount: 179, commentsCount: 115, postType: 'text', postText: `Rerum rerum corporis optio aliquam in dolorum tempora et. Perspiciatis a est iure. Temporibus accusamus sit.

Occaecati cupiditate reprehenderit est eos incidunt. Repellat magni quos est qui sunt dolorum sint. Dignissimos tempore tempora tempora quo sit id et omnis eius. Et et qui eius quidem facere. Nam deleniti voluptates nisi.

Sunt consequatur quidem et possimus. Quaerat aspernatur eum sint ipsa consectetur. Quia ullam enim optio. Veritatis quo rerum veniam tenetur sit aut. Eius natus voluptates eos et molestias sint commodi possimus facere. Qui rerum harum perspiciatis.`, imageURL: null, postTitle: "Distinctio exercitationem suscipit non est ut voluptas officia temporibus numquam. Cupiditate facilis ut optio non. Dolor sit in quasi odit placeat nobis pariatur. Perferendis sit vel.", userName: 'Monty Hauck', bakeryName: 'b/Sourdough', timePosted: 'Sun Feb 17 2019 07:11:51 GMT-0800 (Pacific Standard Time)' },
];

export default samplePosts;